baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-astatine-theme'
publishDir = 'docs'
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
[taxonomies]
    category = "categories"  
    tag = "tags"
[permalinks]
    post = "/:slug/"
    page = "/:slug/"
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -130
[params]
	description = """The homepage of Astatine."""
	authorName = "London Dixon"
	[params.imgname]
		name = "img/main.jpg"
		alt = "Profile picture"
	blogrss = true
[sitemap]
filename = "sitemap.xml"
